#!/usr/bin/env bash
#
# Description: Master builder script :)
#
# Homepage: https://git.sr.ht/~krathalan/miscellaneous-scripts
#
# Copyright (C) 2020 Hunter Peavey
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------------------
# -------------- Guidelines ---------------
# -----------------------------------------

# This script follows the Google Shell Style Guide:
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

# Colors
readonly RED=$(tput bold && tput setaf 1)
readonly NC=$(tput sgr0) # No color/turn off all tput attributes

# Other
readonly BUILD_USER="builder"
readonly MASTER_BUILD_DIR="/home/${BUILD_USER}/aur"
readonly CCACHE_DIR="/home/${BUILD_USER}/.cache/ccache"
readonly MAKECHROOTPKG_DIR="/var/lib/makechrootpkg"
readonly SIGNING_KEY="1C52FC395F059E60180BB53BCD9097F0E64296BB"
readonly SCRIPT_NAME="${0##*/}"

# -----------------------------------------
# ------------- User variables ------------
# -----------------------------------------

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

# Removes old packages built with make(chroot)pkg
clean_pkgbuild_dirs()
{
  local -r dirsToClean=("${MASTER_BUILD_DIR}")
  local toClean

  for directory in "${dirsToClean[@]}"; do
    if [[ -d "${directory}" ]]; then
      mapfile -t toClean <<< "$(find "${directory}" -type f \( -name "*.gz" -o -name "*.xz" -o -name "*.zst" -o -name "*.lz4" -o -name "*.log" -o -name "*.sig" \))"

      for file in "${toClean[@]}"; do
        rm -f "${file}"
      done
    else
      printf "\nSkipping %s, does not exist\n" "${directory}"
    fi
  done
}

#######################################
# Prints passed error message before premature exit.
# Prints everything to >&2 (STDERR).
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
exit_script_on_failure()
{
  printf "%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
  exit 1
}

#######################################
# Prints an info message.
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
print_info()
{
  printf "Info: %s\n" "$1"
}

# -----------------------------------------
# ---------------- Script -----------------
# -----------------------------------------

# makechrootpkg -c -u -d ${CCACHE_DIR}/:/ccache -r /var/lib/makechrootpkg -- CCACHE_DIR=/ccache

[[ "$(whoami)" = "root" ]] &&
  exit_script_on_failure "This script should NOT be run as root (or sudo)!"

[[ -z "${MASTER_BUILD_DIR:-}" ]] &&
  exit_script_on_failure "Please set an environment variable \$MASTER_BUILD_DIR defining the directory containing all package directories (e.g. \"/home/builder/aur\")."

if [[ ! -e "${CCACHE_DIR}" ]]; then
  print_info "Making \$CCACHE_DIR ${CCACHE_DIR} directory"
  mkdir -p "${CCACHE_DIR}"
fi

if ! pacman -Qq devtools > /dev/null; then
  exit_script_on_failure "Please install the \'devtools\' package"
fi

if [[ ! -e "${MAKECHROOTPKG_DIR}" ]]; then
  print_info "Makechrootpkg dir ${MAKECHROOTPKG_DIR} doesn't exist; making it..."
  mkdir -p "${MAKECHROOTPKG_DIR}"
  mkarchroot "${MAKECHROOTPKG_DIR}"/root base-devel
  print_info "Done making ${MAKECHROOTPKG_DIR} makechrootpkg dir."
fi

print_info "Cleaning out master package directory before we begin building"
clean_pkgbuild_dirs

for directory in "${MASTER_BUILD_DIR:-}"/*; do
  if [[ -d "${directory}" ]]; then
    cd "${directory}" || exit_script_on_failure "Failed to \`cd\` into ${directory}"

    # Check out a fresh pkgbuild; pull any diffs
    git checkout PKGBUILD
    git_output="$(git pull)"

    if [[ "${git_output}" == *"Already up to date."* ]] && [[ "${directory}" != *"git"* ]]; then
      print_info "No need to build ${directory##*/}, it is already up-to-date and is not a -git package; skipping"
      continue
    fi

    print_info "Building package ${directory##*/}"

    # -c: Clean the chroot before building
    # -u: Update the working copy of the chroot before building
    # -d: Bind directory into build chroot as read-write
    # -r: The chroot dir to use
    # Arguments passed to makechrootpkg after the
    # end-of-options marker (--) will be passed to makepkg. 
    makechrootpkg -c -u -d ${CCACHE_DIR}/:/ccache -r ${MAKECHROOTPKG_DIR} -- CCACHE_DIR=/ccache

    for package in "${PWD}"/*.pkg.tar.zst; do
      if [[ -f "/var/cache/pacman/pkg/${package##*/}" ]]; then
        print_info "Package ${package##*/} is already built; skipping"
        continue
      fi

      print_info "Copying package to local pacman cache"
      sudo cp "${package}" /var/cache/pacman/pkg/
      sudo chown root:root /var/cache/pacman/pkg/"${package##*/}"

      print_info "Signing package and uploading to builds.krathalan.net"
      gpg --default-key "${SIGNING_KEY}" --output "$1.sig" --detach-sig "$1"
      
      sleep 2
      rsync "${package}" "${package}.sig" krack-receive@krathalan.net:~/package-dropbox
    done
  fi
done