#!/usr/bin/env bash
#
# Description: Master builder script :)
#
# Homepage: https://git.sr.ht/~krathalan/miscellaneous-scripts
#
# Copyright (C) 2020 Hunter Peavey
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------------------
# -------------- Guidelines ---------------
# -----------------------------------------

# This script follows the Google Shell Style Guide:
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

# Misc
NEXT_WAKE=""

# Source a lot of common (between krack scripts) variables
# shellcheck disable=SC1091
source /usr/lib/krack/common

# Source user conf
# shellcheck disable=SC1091
source /etc/krack/build.conf

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

check_awaken_request()
{
  if [[ -f "${STATUS_DIR}/krack-request-awaken" ]]; then
    # Clean up request file
    rm -f "${STATUS_DIR}/krack-request-awaken"
    # Clean up our sleeping child....
    kill "${sleep_pid}"
    return 0 # Awaken!
  else
    return 1 # Slumber...
  fi
}

# Removes old packages built with make(chroot)pkg
clean_pkgbuild_dirs()
{
  local -r dirsToClean=("${MASTER_BUILD_DIR}")
  local toClean

  for directory in "${dirsToClean[@]}"; do
    if [[ -d "${directory}" ]]; then
      mapfile -t toClean <<< "$(find "${directory}" -type f \( -name "*.gz" -o -name "*.xz" -o -name "*.zst" -o -name "*.lz4" -o -name "*.log" -o -name "*.sig" \))"

      for file in "${toClean[@]}"; do
        rm -f "${file}"
      done
    else
      printf "\nSkipping %s, does not exist\n" "${directory}"
    fi
  done
}

#######################################
# Prints passed error message before premature exit.
# Prints everything to >&2 (STDERR).
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
exit_script_on_failure()
{
  state "death"
  printf "%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
  exit 1
}

#######################################
# Prints an info message.
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
print_info()
{
  printf "%sInfo:%s %s\n" "${WHITE}" "${NC}" "$1"
}

# Stuff for $(krackctl status)

important()
{
  printf "%s" "$1" > "${STATUS_IMPORTANT_MESSAGE_FILE}"
  printf "%s!!!!: %s%s\n" "${RED}" "$1" "${NC}"
}

state()
{
  case "$1" in
    starting) state_helper "starting up..." ;;
    death) state_helper "pronounced dead at $(date). Kitty is sad 😿" ;;
    sleeping) state_helper "sleeping until ${NEXT_WAKE}" ;;
    building) state_helper "building (started at $(date +%r))" 
              date +%s > "${STATUS_DATE_BUILD_START_FILE}"
              ;;
    *) state_helper "unknown. Contact developer at srht@krathalan.net" ;;
  esac
}

state_helper()
{
  printf "%s" "$1" > "${STATUS_STATE_FILE}"
}

substate()
{
  case "$1" in
    making) substate_helper "making ${current_package} package (started at $(date +%r))" 
            date +%s > "${STATUS_DATE_MAKE_START_FILE}"
            ;;
    preparing) substate_helper "preparing for build" ;;
    uploading) substate_helper "uploading built ${current_package} package" ;;
  esac
}

substate_helper()
{
  printf "%s" "$1" > "${STATUS_SUBSTATE_FILE}"
}

# -----------------------------------------
# ---------------- Script -----------------
# -----------------------------------------

[[ "$(whoami)" == "root" ]] &&
  exit_script_on_failure "This script should NOT be run as root (or sudo)!"

# Ensure all important directories exist
mkdir -p "${MASTER_BUILD_DIR}" \
         "${CCACHE_DIR}" \
         "${LOG_DIR}" \
         "${PKG_CACHE_DIR}" \
         "${STATUS_DIR}"

state "starting"
printf "nothing yet :)" > "${STATUS_IMPORTANT_MESSAGE_FILE}"

if [[ ! -e "${MAKECHROOTPKG_DIR}" ]]; then
  exit_script_on_failure "Makechrootpkg dir ${MAKECHROOTPKG_DIR} doesn't exist. Please run \`sudo krackctl create-chroot\`."
fi

if [[ "$*" == *"--start-asleep"* ]]; then
  readonly START_ASLEEP="true"
else
  readonly START_ASLEEP="false"
fi

SKIP_COMPLETE="false"

while true; do
  state "building"
  print_info "${CYAN}Good morning, it is $(date) and it's time to build packages again${NC}"

  if [[ "${SKIP_COMPLETE}" == "false" ]] && [[ "${START_ASLEEP}" == "true" ]]; then
    print_info "Oh boy, extra naps! Starting asleep"
    SKIP_COMPLETE="true"
  else
    print_info "Cleaning out master package directory before we begin building"
    clean_pkgbuild_dirs

    for directory in "${MASTER_BUILD_DIR:-}"/*; do
      if [[ -d "${directory}" ]]; then
        cd "${directory}" || exit_script_on_failure "Failed to \`cd\` into ${directory}"
        current_package="${directory##*/}"

        substate "preparing"

        if [[ -f "${PWD}/krack-prepull.sh" ]]; then
          print_info "Executing krack-prepull.sh"
          # shellcheck disable=SC1090
          source "${PWD}/krack-prepull.sh"
        fi

        # Check out a fresh pkgbuild; pull any diffs
        git checkout PKGBUILD &> /dev/null
        git_output="$(git pull)"

        if [[ -f "${PWD}/krack-postpull.sh" ]]; then
          print_info "Executing krack-postpull.sh"
          # shellcheck disable=SC1090
          source "${PWD}/krack-postpull.sh"
        fi

        if [[ -f "${PWD}/krack-request-build" ]]; then
          rm -f "${PWD}/krack-request-build"
          print_info "Build was requested manually; proceeding with build"
        elif [[ "${git_output}" == *"Already up to date."* ]] && [[ "${directory}" != *"git"* ]]; then
          print_info "No need to build ${current_package}, it is already ${GREEN}up-to-date${NC} and is not a -git package; skipping"
          continue
        fi

        if [[ "${directory}" == *"git"* ]]; then
          print_info "${current_package} is a -git package; ${BLUE}forcing update${NC}"
        fi

        substate "making"
        print_info "${BLUE}Building package ${current_package}${NC}"

        # Disable some safety stuff here to provide nice output and continue building other packages if one build fails
        set +Ee

        # -c: Clean the chroot before building
        # -u: Update the working copy of the chroot before building
        # -d: Bind directory into build chroot as read-write
        # -r: The chroot dir to use
        # Arguments passed to makechrootpkg after the
        # end-of-options marker (--) will be passed to makepkg. 
        makechrootpkg -c -u -d "${CCACHE_DIR}"/:/ccache -r "${MAKECHROOTPKG_DIR}" -- CCACHE_DIR=/ccache
        build_outcome=$?

        # Re-enforce safe exiting
        set -Ee

        # If the build failed...
        if [[ "${build_outcome}" != 0 ]]; then
          important "Build for ${current_package} failed at $(date)"

          [[ -f "${PWD}/krack-postbuild.sh" ]] && \
            print_info "Skipping postbuild script due to build failure"

          print_info "Continuing to the next build"
          continue
        fi

        if [[ -f "${PWD}/krack-postbuild.sh" ]]; then
          print_info "Executing krack-postbuild.sh"
          # shellcheck disable=SC1090
          source "${PWD}/krack-postbuild.sh"
        fi

        for package_tarball in "${PWD}"/*.pkg.tar.zst; do
          if [[ -f "${PKG_CACHE_DIR}/${current_package}" ]]; then
            print_info "${YELLOW}Package ${current_package} with the same version is already in the krack pkgcache; the cat is mildly annoyed 😾${NC}"
            continue
          fi

          print_info "Copying package to local krack-build pkgcache"
          cp "${package_tarball}" "${PKG_CACHE_DIR}"

          print_info "Signing package and uploading to ${DROPBOX_PATH}"
          gpg --default-key "${SIGNING_KEY}" --output "${package_tarball}.sig" --detach-sig "${package_tarball}"
          
          # Sleep for 2 seconds; sometimes the rsync command starts before the sig file has appeared on slower devices
          sleep 2
          rsync -a --progress "${package_tarball}" "${package_tarball}.sig" "${DROPBOX_PATH}"

          print_info "${GREEN}Package ${current_package} built successfully; please give your cat a treat 😻${NC}"
        done
      fi
    done

    print_info "It is $(date) and all packages have finished building"
  fi
  
  NEXT_WAKE="$(date -d "$(date)+24 hours")"
  state "sleeping"
  print_info "The next daily package rebuild will occur 24 hours from now at ${NEXT_WAKE}"
  # Custom printf here because we don't want a new line (for the spinner) :)
  printf "%sInfo:%s %sNapping until then...%s " "${WHITE}" "${NC}" "${PURPLE}" "${NC}"

  # https://unix.stackexchange.com/questions/225179/display-spinner-while-waiting-for-some-process-to-finish/225183#225183
  sleep 86400 &
  sleep_pid=$!
  i=1
  sp="/-\|"
  echo -n ' '
  while [[ -d "/proc/$sleep_pid" ]];  do
    printf "\b%s" ${sp:i++%${#sp}:1}

    if check_awaken_request; then
      break
    fi

    sleep 0.75
  done

  printf "\n"
done